// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path=".snaplet/snaplet.d.ts" />
// This config was generated by Snaplet make sure to check it over before using it.
import { copycat } from "@snaplet/copycat";
import { defineConfig } from "snaplet";
export default defineConfig({
  transform: {
    $mode: "unsafe",
    public: {
      titles({ row }) {
        return {
          dateWatched: copycat.dateString(row.dateWatched),
          dateAdded: copycat.dateString(row.dateAdded),
        };
      },
      users({ row }) {
        return {
          name: copycat.firstName(row.name),
        };
      },
    },
  },
  subset: {
    enabled: true,
    targets: [
      {
        table: "public.titles",
        rowLimit: 100,
      },
      {
        table: "public.titles_to_users",
        rowLimit: 100,
      },
    ],
    maxCyclesLoop: 0,
    eager: false,
  },
});
